import { writeFile, access } from "node:fs/promises";

const TEAM_ID = 424985;
const TEAM_URL = `https://ctftime.org/team/${TEAM_ID}`;
const API_URL = `https://ctftime.org/api/v1/teams/${TEAM_ID}/`;
const OUTPUT_PATH = new URL("../src/data/ctftime.generated.ts", import.meta.url);
const USER_AGENT =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/125 Safari/537.36";

const paletteCycle = ["ember", "signal", "mint", "violet", "sand", "red"];

async function fetchText(url) {
  const response = await fetch(url, {
    headers: {
      "User-Agent": USER_AGENT,
      Accept: "text/html,application/json;q=0.9,*/*;q=0.8",
    },
  });

  if (!response.ok) {
    throw new Error(`${url} returned HTTP ${response.status}`);
  }

  return response.text();
}

function decodeHtml(value) {
  return value
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(Number(code)))
    .replace(/&#x([\da-f]+);/gi, (_, code) => String.fromCharCode(Number.parseInt(code, 16)))
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\s+/g, " ")
    .trim();
}

function stripTags(value) {
  return decodeHtml(value.replace(/<[^>]+>/g, " "));
}

function parseRatingYear(team) {
  const years = Object.keys(team.rating ?? {})
    .map(Number)
    .filter((year) => Number.isFinite(year))
    .sort((a, b) => b - a);

  for (const year of years) {
    const rating = team.rating[String(year)];
    if (rating?.rating_points || rating?.rating_place || rating?.country_place) {
      return [String(year), rating];
    }
  }

  return [String(new Date().getFullYear()), {}];
}

function parseUpcomingEvents(html) {
  const section = html.match(/<h3>Plan to participate in CTF events<\/h3>([\s\S]*?)<\/table>/);
  if (!section) return [];

  return [...section[1].matchAll(/<tr><td><a href="([^"]+)">([\s\S]*?)<\/a><\/td><td>([\s\S]*?)<\/td><\/tr>/g)].map(
    ([, href, name, date]) => ({
      name: decodeHtml(name),
      date: stripTags(date),
      href: new URL(href, TEAM_URL).href,
    }),
  );
}

function parseRankings(html) {
  return [...html.matchAll(/<div class="tab-pane(?: active)?" id="rating_(\d{4})">([\s\S]*?)<\/table>/g)].flatMap(
    ([, year, section]) =>
      [
        ...section.matchAll(
          /<tr><td class="place_ico"><\/td><td class="place">(\d+)<\/td><td><a href="([^"]+)">([\s\S]*?)<\/a><\/td><td>([\s\S]*?)<\/td><td>([\s\S]*?)<\/td><\/tr>/g,
        ),
      ].map(([, place, href, event, points, rating]) => ({
        event: decodeHtml(event),
        place: Number(place),
        points: stripTags(points),
        rating: stripTags(rating),
        year,
        type: "online",
        href: new URL(href, TEAM_URL).href,
      })),
  );
}

function parseMembers(html) {
  const section = html.match(/<div class="tab-pane active" id="recent_members">([\s\S]*?)<\/table>/);
  if (!section) return [];

  return [...section[1].matchAll(/<tr><td><a href="([^"]+)">([\s\S]*?)<\/a><\/td><\/tr>/g)].map(
    ([, href, username], index) => ({
      username: decodeHtml(username),
      role: "ctftime member",
      bio: "Current roster member pulled from the CTFtime team profile.",
      palette: paletteCycle[index % paletteCycle.length],
      href: new URL(href, TEAM_URL).href,
    }),
  );
}

function serialize(value) {
  return JSON.stringify(value, null, 2);
}

async function hasExistingOutput() {
  try {
    await access(OUTPUT_PATH);
    return true;
  } catch {
    return false;
  }
}

async function main() {
  try {
    const [apiText, html] = await Promise.all([fetchText(API_URL), fetchText(TEAM_URL)]);
    const team = JSON.parse(apiText);
    const [ratingYear, rating] = parseRatingYear(team);
    const rankings = parseRankings(html);
    const upcomingEvents = parseUpcomingEvents(html);
    const ctftimeMembers = parseMembers(html);
    const generatedAt = new Date().toISOString();

    const output = `// Generated by scripts/update-ctftime.mjs. Do not edit by hand.
export type Ranking = {
  event: string;
  place: number;
  points: string;
  rating: string;
  year: string;
  type: "finals" | "quals" | "online";
  href: string;
};

export type UpcomingEvent = {
  name: string;
  date: string;
  href: string;
};

export type CtftimeMember = {
  username: string;
  role: string;
  bio: string;
  palette: "ember" | "signal" | "mint" | "violet" | "sand" | "red";
  href: string;
};

export const ctftimeGeneratedAt = ${serialize(generatedAt)};

export const teamProfile = ${serialize({
  id: team.id,
  name: team.primary_alias ?? team.name,
  canonicalName: team.name,
  country: team.country,
  logo: team.logo,
  aliases: team.aliases ?? [],
  academic: Boolean(team.academic),
  sourceHref: TEAM_URL,
})} as const;

export const ratingSnapshot = ${serialize({
  globalRank: String(rating.rating_place ?? "n/a"),
  localRank: String(rating.country_place ?? "n/a"),
  ratingPoints:
    typeof rating.rating_points === "number" ? rating.rating_points.toFixed(3) : String(rating.rating_points ?? "0.000"),
  year: ratingYear,
  source: "ctftime.org/team/424985",
  sourceHref: TEAM_URL,
})} as const;

export const upcomingEvents: UpcomingEvent[] = ${serialize(upcomingEvents)};

export const rankings: Ranking[] = ${serialize(rankings)};

export const ctftimeMembers: CtftimeMember[] = ${serialize(ctftimeMembers)};
`;

    await writeFile(OUTPUT_PATH, output);
    console.log(
      `Updated CTFtime data: ${rankings.length} rankings, ${upcomingEvents.length} planned events, ${ctftimeMembers.length} members.`,
    );
  } catch (error) {
    if (await hasExistingOutput()) {
      console.warn(`Could not update CTFtime data, keeping existing generated file: ${error.message}`);
      return;
    }
    throw error;
  }
}

await main();
