// Generated by scripts/update-ctftime.mjs. Do not edit by hand.
export type Ranking = {
  event: string;
  place: number;
  points: string;
  rating: string;
  year: string;
  type: "finals" | "quals" | "online";
  href: string;
};

export type UpcomingEvent = {
  name: string;
  date: string;
  href: string;
};

export type CtftimeMember = {
  username: string;
  role: string;
  bio: string;
  palette: "ember" | "signal" | "mint" | "violet" | "sand" | "red";
  href: string;
};

export const ctftimeGeneratedAt = "2026-05-26T09:51:30.656Z";

export const teamProfile = {
  "id": 424985,
  "name": "G4mra",
  "canonicalName": "0x4X10M",
  "country": "EG",
  "logo": "https://ctftime.org//media/team/image_87.png",
  "aliases": [
    "7anzala",
    "G4mra"
  ],
  "academic": false,
  "sourceHref": "https://ctftime.org/team/424985"
} as const;

export const ratingSnapshot = {
  "globalRank": "65",
  "localRank": "3",
  "ratingPoints": "349.573",
  "year": "2026",
  "source": "ctftime.org/team/424985",
  "sourceHref": "https://ctftime.org/team/424985"
} as const;

export const upcomingEvents: UpcomingEvent[] = [
  {
    "name": "ASIS CTF Quals 2026",
    "date": "Aug. 29, 2026, 2 p.m.",
    "href": "https://ctftime.org/event/3033"
  }
];

export const rankings: Ranking[] = [
  {
    "event": "0xV01D CTF 2026",
    "place": 3,
    "points": "8843.0000",
    "rating": "0.000 *",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3269"
  },
  {
    "event": "TJCTF 2026",
    "place": 56,
    "points": "10190.0000",
    "rating": "43.988",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3195"
  },
  {
    "event": "Midnight Sun CTF 2026 Quals",
    "place": 65,
    "points": "2571.0000",
    "rating": "32.959",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/2773"
  },
  {
    "event": "THCon 2K26 CTF",
    "place": 35,
    "points": "1849.0000",
    "rating": "8.079",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3186"
  },
  {
    "event": "CTF@AC26 - Quals",
    "place": 79,
    "points": "400.0000",
    "rating": "3.238",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3192"
  },
  {
    "event": "UMDCTF 2026",
    "place": 35,
    "points": "1915.0000",
    "rating": "42.504",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3056"
  },
  {
    "event": "pingCTF 2026",
    "place": 21,
    "points": "1635.0000",
    "rating": "23.994",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3147"
  },
  {
    "event": "b01lers CTF 2026",
    "place": 69,
    "points": "4650.0000",
    "rating": "27.671",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3153"
  },
  {
    "event": "BlueHens CTF 2026",
    "place": 40,
    "points": "2030.0000",
    "rating": "21.271",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3235"
  },
  {
    "event": "CTF@CIT 2026",
    "place": 47,
    "points": "27594.0000",
    "rating": "14.683",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3156"
  },
  {
    "event": "Incognito 7.0",
    "place": 31,
    "points": "2950.0000",
    "rating": "10.113",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3225"
  },
  {
    "event": "UMassCTF 2026",
    "place": 118,
    "points": "2400.0000",
    "rating": "33.080",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/2937"
  },
  {
    "event": "DawgCTF 2026",
    "place": 95,
    "points": "8410.0000",
    "rating": "46.045",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3102"
  },
  {
    "event": "NCTF 2026",
    "place": 274,
    "points": "600.0000",
    "rating": "2.889",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3206"
  },
  {
    "event": "Kashi CTF 2026",
    "place": 16,
    "points": "5088.0000",
    "rating": "16.060",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3150"
  },
  {
    "event": "VishwaCTF'2026",
    "place": 54,
    "points": "7350.0000",
    "rating": "17.545",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3197"
  },
  {
    "event": "VolgaCTF 2026 Qualifier",
    "place": 198,
    "points": "200.0000",
    "rating": "3.771",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3045"
  },
  {
    "event": "Codegate CTF 2026 Preliminary",
    "place": 237,
    "points": "500.0000",
    "rating": "5.953",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3131"
  },
  {
    "event": "TexSAW 2026",
    "place": 87,
    "points": "2041.0000",
    "rating": "16.148",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3130"
  },
  {
    "event": "Undutmaning 2026",
    "place": 34,
    "points": "2236.0000",
    "rating": "25.124",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/2987"
  },
  {
    "event": "TAMUctf 2026",
    "place": 98,
    "points": "1381.0000",
    "rating": "52.938",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3095"
  },
  {
    "event": "UNbreakable International 2026 - Team Phase",
    "place": 107,
    "points": "99.0000",
    "rating": "0.586",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3172"
  },
  {
    "event": "EHAX CTF 2026",
    "place": 166,
    "points": "1067.0000",
    "rating": "2.781",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3127"
  },
  {
    "event": "UniVsThreats 26 Quals CTF",
    "place": 77,
    "points": "585.0000",
    "rating": "3.335",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3092"
  },
  {
    "event": "RamadanCTF 2026",
    "place": 136,
    "points": "125.0000",
    "rating": "0.000",
    "year": "2026",
    "type": "online",
    "href": "https://ctftime.org/event/3135"
  }
];

export const ctftimeMembers: CtftimeMember[] = [
  {
    "username": "0xcraches",
    "role": "ctftime member",
    "bio": "Current roster member pulled from the CTFtime team profile.",
    "palette": "ember",
    "href": "https://ctftime.org/user/217421"
  },
  {
    "username": "amrk",
    "role": "ctftime member",
    "bio": "Current roster member pulled from the CTFtime team profile.",
    "palette": "signal",
    "href": "https://ctftime.org/user/232300"
  },
  {
    "username": "0xb4raa",
    "role": "ctftime member",
    "bio": "Current roster member pulled from the CTFtime team profile.",
    "palette": "mint",
    "href": "https://ctftime.org/user/250146"
  },
  {
    "username": "Z4faran",
    "role": "ctftime member",
    "bio": "Current roster member pulled from the CTFtime team profile.",
    "palette": "violet",
    "href": "https://ctftime.org/user/251499"
  },
  {
    "username": "khaled1hunter",
    "role": "ctftime member",
    "bio": "Current roster member pulled from the CTFtime team profile.",
    "palette": "sand",
    "href": "https://ctftime.org/user/252263"
  },
  {
    "username": "0xzero4",
    "role": "ctftime member",
    "bio": "Current roster member pulled from the CTFtime team profile.",
    "palette": "red",
    "href": "https://ctftime.org/user/253688"
  },
  {
    "username": "RylenAnil",
    "role": "ctftime member",
    "bio": "Current roster member pulled from the CTFtime team profile.",
    "palette": "ember",
    "href": "https://ctftime.org/user/254907"
  }
];
